services:
  - type: web
    name: ocr-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-ara
      pip install -r requirements.txt
    startCommand: python app.py
